[project]
name = "retail_sop"
authors = [
    { name = "Micronxt", email = "vijay@micronxt.com"}
]
description = "Multi-outlet food court SOP & compliance checklist system"
requires-python = ">=3.10"
readme = "README.md"
dynamic = ["version"]
dependencies = [
    "PyJWT~=2.8.0",
]

[build-system]
requires = ["flit_core>=3.4,<4"]
build-backend = "flit_core.buildapi"

[tool.bench.dev-dependencies]

[tool.ruff]
line-length = 110
target-version = "py310"

[tool.ruff.lint]
select = [
    "F",
    "E",
    "W",
    "I",
]
ignore = [
    "B017",
    "B023",
    "B028",
]
